/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinksRouteImport } from './routes/links'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DealersRouteImport } from './routes/dealers'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealerNameRouteImport } from './routes/dealer.$name'
import { Route as CustomerNameRouteImport } from './routes/customer.$name'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DealersRoute = DealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerNameRoute = DealerNameRouteImport.update({
  id: '/dealer/$name',
  path: '/dealer/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerNameRoute = CustomerNameRouteImport.update({
  id: '/customer/$name',
  path: '/customer/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/collections': typeof CollectionsRoute
  '/customers': typeof CustomersRoute
  '/dealers': typeof DealersRoute
  '/insights': typeof InsightsRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/sales': typeof SalesRoute
  '/terms': typeof TermsRoute
  '/customer/$name': typeof CustomerNameRoute
  '/dealer/$name': typeof DealerNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/collections': typeof CollectionsRoute
  '/customers': typeof CustomersRoute
  '/dealers': typeof DealersRoute
  '/insights': typeof InsightsRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/sales': typeof SalesRoute
  '/terms': typeof TermsRoute
  '/customer/$name': typeof CustomerNameRoute
  '/dealer/$name': typeof DealerNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/collections': typeof CollectionsRoute
  '/customers': typeof CustomersRoute
  '/dealers': typeof DealersRoute
  '/insights': typeof InsightsRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/sales': typeof SalesRoute
  '/terms': typeof TermsRoute
  '/customer/$name': typeof CustomerNameRoute
  '/dealer/$name': typeof DealerNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/collections'
    | '/customers'
    | '/dealers'
    | '/insights'
    | '/links'
    | '/login'
    | '/more'
    | '/privacy'
    | '/sales'
    | '/terms'
    | '/customer/$name'
    | '/dealer/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/collections'
    | '/customers'
    | '/dealers'
    | '/insights'
    | '/links'
    | '/login'
    | '/more'
    | '/privacy'
    | '/sales'
    | '/terms'
    | '/customer/$name'
    | '/dealer/$name'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/collections'
    | '/customers'
    | '/dealers'
    | '/insights'
    | '/links'
    | '/login'
    | '/more'
    | '/privacy'
    | '/sales'
    | '/terms'
    | '/customer/$name'
    | '/dealer/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  CollectionsRoute: typeof CollectionsRoute
  CustomersRoute: typeof CustomersRoute
  DealersRoute: typeof DealersRoute
  InsightsRoute: typeof InsightsRoute
  LinksRoute: typeof LinksRoute
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  PrivacyRoute: typeof PrivacyRoute
  SalesRoute: typeof SalesRoute
  TermsRoute: typeof TermsRoute
  CustomerNameRoute: typeof CustomerNameRoute
  DealerNameRoute: typeof DealerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealers': {
      id: '/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof DealersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer/$name': {
      id: '/dealer/$name'
      path: '/dealer/$name'
      fullPath: '/dealer/$name'
      preLoaderRoute: typeof DealerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/$name': {
      id: '/customer/$name'
      path: '/customer/$name'
      fullPath: '/customer/$name'
      preLoaderRoute: typeof CustomerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  CollectionsRoute: CollectionsRoute,
  CustomersRoute: CustomersRoute,
  DealersRoute: DealersRoute,
  InsightsRoute: InsightsRoute,
  LinksRoute: LinksRoute,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  PrivacyRoute: PrivacyRoute,
  SalesRoute: SalesRoute,
  TermsRoute: TermsRoute,
  CustomerNameRoute: CustomerNameRoute,
  DealerNameRoute: DealerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
