// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

type Claims = { sub?: string; exp?: number } & Record<string, unknown>;

// A verified token stays verified until it expires, so a warm instance only
// pays the network verification once per token instead of once per request.
const claimsCache = new Map<string, { claims: Claims; expiresAt: number }>();
const CLAIMS_CACHE_MAX = 500;

async function verifiedClaims(
  token: string,
  verify: () => Promise<{ data: { claims: Claims } | null; error: unknown }>,
): Promise<Claims | null> {
  const now = Date.now();
  const hit = claimsCache.get(token);
  if (hit && hit.expiresAt > now) return hit.claims;
  if (hit) claimsCache.delete(token);

  const { data, error } = await verify();
  if (error || !data?.claims) return null;
  const claims = data.claims;
  const expiresAt = typeof claims.exp === "number" ? claims.exp * 1000 : now + 5 * 60_000;
  if (expiresAt > now) {
    if (claimsCache.size >= CLAIMS_CACHE_MAX) {
      const oldest = claimsCache.keys().next().value;
      if (oldest) claimsCache.delete(oldest);
    }
    claimsCache.set(token, { claims, expiresAt });
  }
  return claims;
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const claims = await verifiedClaims(token, () => supabase.auth.getClaims(token));
    if (!claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    return next({
      context: {
        supabase,
        userId: claims.sub,
        claims,
      },
    });
  },
);
